# File: docker-compose.yml

version: '3'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    ports:
      - "5432:5432"

  apollo:
    build:
      context: .
      dockerfile: Dockerfile.apollo
    ports:
      - "4000:4000"
    depends_on:
      - postgres

  react-native:
    build:
      context: .
      dockerfile: Dockerfile.react-native
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    depends_on:
      - apollo
